services:
  database:
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - docker-tag-monitor:/var/lib/postgresql/data

volumes:
  docker-tag-monitor:
    driver: local
