apiVersion: v2
name: docker-tag-monitor
description: Very simple chart for the Docker Tag Monitor application.

type: application

version: 0.0.1

appVersion: "2025.10.10"

dependencies:
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.0.11
  - name: valkey
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 2.0.2
