apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-tag-monitor.fullname" . }}-backend
  labels:
    {{- include "docker-tag-monitor.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "docker-tag-monitor.selectorLabels" . | nindent 4 }}
    service: backend
