"""add scraped images table

Revision ID: 1460172de75d
Revises: cb274ce175a4
Create Date: 2025-03-30 17:20:38.259975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1460172de75d'
down_revision: Union[str, None] = 'cb274ce175a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('known_tags', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint', 'image', name='endpoint_with_image')
    )
    with op.batch_alter_table('image_to_scrape', schema=None) as batch_op:
        batch_op.create_index('compound_index_endpoint_image', ['endpoint', 'image'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_to_scrape', schema=None) as batch_op:
        batch_op.drop_index('compound_index_endpoint_image')

    op.drop_table('scraped_image')
    # ### end Alembic commands ###
