"""add ImageToScrape.last_viewed

Revision ID: 25bafe5405ce
Revises: 6844092b1f30
Create Date: 2024-11-16 15:49:28.071571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '25bafe5405ce'
down_revision: Union[str, None] = '6844092b1f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_to_scrape', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_viewed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('image_update', schema=None) as batch_op:
        batch_op.drop_constraint('image_update_image_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'image_to_scrape', ['image_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_update', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('image_update_image_id_fkey', 'image_to_scrape', ['image_id'], ['id'])

    with op.batch_alter_table('image_to_scrape', schema=None) as batch_op:
        batch_op.drop_column('last_viewed')

    # ### end Alembic commands ###
