"""add last_pushed

Revision ID: 8f9226e14543
Revises: 1460172de75d
Create Date: 2025-12-23 15:25:32.574994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8f9226e14543'
down_revision: Union[str, None] = '1460172de75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_to_scrape', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_pushed', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_image_to_scrape_last_pushed'), ['last_pushed'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_to_scrape', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_image_to_scrape_last_pushed'))
        batch_op.drop_column('last_pushed')

    # ### end Alembic commands ###
