name: Publish Docker images

on:
  workflow_dispatch: { }

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to the GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute frontend Docker tags
        id: meta_frontend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/docker-tag-monitor-frontend
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYY.MM.DD'}}

      - name: Compute backend Docker tags
        id: meta_backend
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/docker-tag-monitor-backend
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYY.MM.DD'}}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
#          platforms: linux/amd64,linux/arm64 // TODO wait for https://github.com/reflex-dev/reflex/issues/4076 to be resolved
          platforms: linux/amd64
          push: true
          target: frontend
          tags: ${{ steps.meta_frontend.outputs.tags }}
          labels: ${{ steps.meta_frontend.outputs.labels }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
#          platforms: linux/amd64,linux/arm64 // TODO wait for https://github.com/reflex-dev/reflex/issues/4076 to be resolved
          platforms: linux/amd64
          push: true
          target: backend
          tags: ${{ steps.meta_backend.outputs.tags }}
          labels: ${{ steps.meta_backend.outputs.labels }}
